### ISSUE TITLE
how to generate labels of ps2.0

### ISSUE THREAD

**Issue by ZJNBFHXK** [dohoseok/context-based-parking-slot-detect#11]
Hi author, may I ask how to generate the labels of ps2.0, since the original labels of ps2.0 don't fit the input format

**Comment by dohoseok** [comment]
I uploaded converted version of ps2.0 in the link below.
https://drive.google.com/file/d/1vM_u_YNFTdv7eHhwn4ExXE98_7BpSa3X/view?usp=sharing

**Comment by ZJNBFHXK** [comment]
> I uploaded converted version of ps2.0 in the link below. https://drive.google.com/file/d/1vM_u_YNFTdv7eHhwn4ExXE98_7BpSa3X/view?usp=sharing

thank you so much, that helps a lot
