### ISSUE TITLE
Machine stuck?

### ISSUE THREAD

**Issue by Zircoz** [dohoseok/context-based-parking-slot-detect#4]
I am at step 3 in "Prepare Dataset". And after converting the images it has just this output:

```
Finished converting the parking_space dataset:
file_idx = 0
file_idx = 1000
file_idx = 2000
file_idx = 3000
file_idx = 4000
```

Now it had been doing "something" for 1.5 hours but I can't seem to figure out what. My machine is not unresponsive. What is it supposed to do next?

P.S. I am noob in ML, object detection, sorry if this query sounds dumb.

**Comment by dohoseok** [comment]
It takes long time for data augmentation.
The number of files in training folder may be increasing now.
I added log in data augmentation.

**Comment by Zircoz** [comment]
> It takes long time for data augmentation.
> The number of files in training folder may be increasing now.
> I added log in data augmentation.

Okayyyy, thank you! 

I will close this issue when it is done, if you don't mind keeping it open for the time being? 

Also, I am using tensorflow 2+ so i am also upgrading the scripts to work with tf2 & can push it to another branch in your repo when done with it ? :D
